### ISSUE TITLE
Stuttering / Choppy Audio with Airpods

### ISSUE THREAD

**Issue by melihcoban** [valnoxy/t440p-oc#14]
macOS 11.4 Big Sur
I connect the Airpods (2nd generation) without a problem with the Bluetooth but while listening to music audio stutters or gets choppy frequently. Also it drops altogether sometimes. I resetted the bluetooth module but it did not helped at all.

**Comment by valnoxy** [comment]
Hey! Do you use the Big Sur config or HeliPort? And if you don't use HeliPort, can you try it with HeliPort? I updated the readme with a guide, how to switch the configs.

**Comment by melihcoban** [comment]
Hi! Issue still persist with the HeliPort. I believe it might have to do something the way Wi-Fi and Bluetooth works together. I disabled the Wi-Fi and used ethernet cable and there is no stutter/choppy audio. I saw that you suggested using HeliPort to fix it, I should try it again to see if I did something wrong.

**Comment by valnoxy** [comment]
I released Version 1.5.1 with updated kexts. Does the issue still exist in this version?

**Comment by melihcoban** [comment]
In the new version I can't boot into macOS, it gives this error: `OC: Configuration requires vault but no vault provided!`

**Comment by valnoxy** [comment]
I re-uploaded the version with the Misc section. It looks like this is a commom issue with the Intel Bluetooth Firmware. I can't really test much, as I don't have the issue with my bluetooth devices. I will keep trying to fix the issue, but I cannot guarantee that it will be fixed.

**Comment by valnoxy** [comment]
Hi, I updated the Intel Bluetooth kexts. Does the issue still exist with Version 1.5.2?

**Comment by melihcoban** [comment]
Hey! Unfortunately it still does that sometimes. My modem only supports 2.4ghz so it might be interfering the bluetooth, I'll try with 5ghz one and report it back.
